name: "The Destroyer"

on:
  pull_request:
    types: [closed]
  schedule:
    - cron: '*/15 * * * *' # Every 15 minutes

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  destroy-pr:
    if: github.event_name == 'pull_request'
    name: "Destroy PR Environment"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./terraform
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: terraform init

      - name: Select Workspace & Destroy
        run: |
          WORKSPACE="pr-${{ github.event.number }}"
          BACKEND_TAG="mustaphatahiru/capstone-backend:pr-${{ github.event.number }}"
          FRONTEND_TAG="mustaphatahiru/capstone-frontend:latest"
          
          # Only destroy if workspace exists
          if terraform workspace select $WORKSPACE; then
            if terraform destroy -auto-approve \
              -var="pr_number=${{ github.event.number }}" \
              -var="backend_image=$BACKEND_TAG" \
              -var="frontend_image=$FRONTEND_TAG" \
              -var="POSTGRES_USER=${{ secrets.POSTGRES_USER }}" \
              -var="POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}" \
              -var="POSTGRES_DB=${{ secrets.POSTGRES_DB }}"; then
              terraform workspace select default
              terraform workspace delete $WORKSPACE
              echo "Successfully destroyed workspace $WORKSPACE"
            else
              echo "ERROR: Destroy failed for workspace $WORKSPACE"
              exit 1
            fi
          else
            echo "Workspace $WORKSPACE does not exist. Skipping destroy."
          fi

  scheduled-cleanup:
    if: github.event_name == 'schedule'
    name: "Scheduled Cleanup (Reaper)"
    runs-on: ubuntu-latest
    
    steps:
      - name: Configure AWS credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: us-east-1

      - name: Find and Terminate Stale Instances
        run: |
            set -euo pipefail  
            
            # Calculate cutoff time (30 minutes ago) in epoch seconds
            CUTOFF_TIME=$(date -u -d '30 minutes ago' +%s)
            echo "Looking for instances older than $(date -u -d '30 minutes ago' '+%Y-%m-%d %H:%M:%S UTC')"
            
            # Get all running instances with phoenix-pr-* tag
            INSTANCES=$(aws ec2 describe-instances \
                --filters "Name=tag:Name,Values=phoenix-pr-*" "Name=instance-state-name,Values=running" \
                --query 'Reservations[].Instances[].[InstanceId,LaunchTime,Tags[?Key==`Name`].Value|[0]]' \
                --output text)
            
            if [ -z "$INSTANCES" ]; then
                echo "No running phoenix-pr-* instances found."
                exit 0
            fi
            
            # Filter instances by launch time
            STALE_INSTANCES=()
            while IFS=$'\t' read -r instance_id launch_time name; do
                # Convert launch time to epoch (remove milliseconds and timezone)
                LAUNCH_EPOCH=$(date -u -d "${launch_time%.*}" +%s)
                
                if [ "$LAUNCH_EPOCH" -le "$CUTOFF_TIME" ]; then
                    echo "Found stale instance: $instance_id (Name: $name, Launched: $launch_time)"
                    STALE_INSTANCES+=("$instance_id")
                fi
            done <<< "$INSTANCES"
            
            # Terminate stale instances
            if [ ${#STALE_INSTANCES[@]} -gt 0 ]; then
                echo "Terminating ${#STALE_INSTANCES[@]} stale instance(s)..."
                aws ec2 terminate-instances --instance-ids "${STALE_INSTANCES[@]}"
                
                echo "Waiting for termination to complete..."
                aws ec2 wait instance-terminated --instance-ids "${STALE_INSTANCES[@]}"
                echo " Successfully terminated ${#STALE_INSTANCES[@]} instance(s)"
            else
                echo "No stale instances found (all instances are less than 30 minutes old)."
            fi
